font_family     Fira Code SemiBold
font_size 		13.0
bold_font       auto
italic_font      auto
bold_italic_font auto

background_opacity 0.5
confirm_os_window_close 0

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4

selection_foreground none
selection_background none

foreground         #F8A6D0
background         #140F1C
cursor             #F8A6D0

active_tab_foreground     #140F1C
active_tab_background     #F8A6D0
inactive_tab_foreground   #F8A6D0
inactive_tab_background   #140F1C

active_border_color   #F8A6D0
inactive_border_color #140F1C
bell_border_color     #493B7C

color0      #3F3949
color1		#493B7C
color2		#803A6C
color3		#853A6B
color4		#973A88
color5		#D93A93
color6		#ED1985
color7		#ED77B3
color8		#A6537D
color9		#493B7C
color10		#803A6C
color11		#853A6B
color12		#973A88
color13		#D93A93
color14		#ED1985
color15		#ED77B3
