#!/bin/bash

vo() 
{
  # kitty --detach --working-directory=${1:-$PWD} -T=NeoVim nvim
    wezterm start --cwd ${1:-$PWD} --class nvim-vo -- nvim &
}

alias cat="bat"
alias vim="nvim"
alias fif="$HOME/git/dotfiles/bin/fit"
alias vpn="$HOME/vpn_l3"
alias my-rclone="$HOME/git/dotfiles/bin/rclone.sh"

# Wayland
alias code="code --enable-features=UseOzonePlatform --ozone-platform=wayland"


# Git
alias gs="git status"
alias gpuoc='git push --set-upstream origin $(git symbolic-ref --short HEAD)'


alias mssql-cli="python3.9 /home/rramos/.local/lib/python3.9/site-packages/mssqlcli/main.py"
