#!/usr/bin/env bash

lauchedBarPositions=()

getMonitorPosition () {
  echo $(echo $1 | grep -oP "\+[0-9]+"| tr -d '[:space:]')
}

getMonitorSize () {
  echo $(echo $1 | grep -oP "[0-9]{4}" | head -n1)
}

launchBar () {
  outputPos=$(getMonitorPosition $1)
  outputSize=$(getMonitorSize $1)

  if [[ ! " ${lauchedBarPositions[@]}" =~ "$outputPos" ]]; then
    echo lauchingBar $output ${outputSize}x22${outputPos}
    lauchedBarPositions+=("$outputPos")
    /usr/local/sbin/admiral -c ~/git/dotfiles/admiral/admiral.toml | lemonbar -b -u 2 -p -B "#00000000" -F "#ffeeeeee" \
      -U "${WALLPAPER_MAIN_COLOR:=#ffeeeeee}" \
      -f "Droid Sans Mono for Powerline:style=Regular:size=10" -f "Font Awesome 5 Brands Regular:size=10" -f "Font Awesome 5 Free Solid:size=10" \
      -g ${outputSize}x22${outputPos} | sh &
  else
    echo Ignoring $output
  fi
}

pkill admiral &>/dev/null
pkill lemonbar &>/dev/null

outputs=($(xrandr --listactivemonitors | awk ' { print $4" "$3 } '))

export output=""
for (( i=0; i<${#outputs[@]}; i += 2))
do
  output=${outputs[i]} # Output name
  launchBar ${outputs[i + 1]}
done

echo Bars lauched
