# GTK
set $gnome-schema org.gnome.desktop.interface
exec_always {
    gsettings set org.gnome.desktop.interface text-scaling-factor 1
    gsettings set org.gnome.desktop.interface cursor-size 34
    gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/IMModule': <'ibus'>}"
}

exec_always ~/git/dotfiles/sway/import-gsettings

# Mouse
seat seat0 xcursor_theme Yaru 34
