
# 
# Aplication x Workspaces
#

assign [title="(?i)firefox"] $ws3
assign [class="(?i)code"] $ws2
assign [class="(?i)rider"] $ws2
assign [app_id="Slack"] $ws4
assign [title="(?i)Microsoft Teams.*"] $ws5
assign [app_id="obsidian"] $ws6
assign [app_id="Logseq"] $ws6

for_window [class="(?i)spotify"] move to workspace $ws9

# Slack Circles
for_window [title="(?i)Círculo:"] inhibit_idle open, move to workspace $ws5, workspace $ws5
                       
for_window [title="gsimplecal"] border pixel

for_window [app_id="org.keepassxc.KeePassXC"] floating enabled

# Microsoft Teams Config.
for_window [title="(?i)Indicador de compartilhamento"] floating enabled
for_window [title="(?i)Microsoft Teams.*"] inhibit_idle open

#for_window [app_id="^chrome-.*-.*$"] shortcuts_inhibitor disable
#for_window [app_id="chromium"] shortcuts_inhibitor disable

for_window [app_id="gnome-calculator"] floating enable, move position cursor

