#!/usr/bin/env bash


battery () {
	battery="$(</sys/class/power_supply/BAT0/capacity)"
	charging="$(</sys/class/power_supply/BAT0/status)"
	charging=[ "$charging" == "Charging" ]
  output=""

	case "$battery" in
		[0-9]|10)
      output="\uf582"
		;;

		1[0-9]|2[0-5])
      if [ $charging ]; then
        output="\uf585"
      else
        output="\uf57A"
      fi
		;;

		2[6-9]|3[0-9]|4[0-9]|50)
      if [ $charging ]; then
        output="\uf587"
      else
        output="\uf57D"
      fi
		;;

		5[1-9]|6[0-9]|7[0-5])
      if [ $charging ]; then
        output="\uf589"
      else
        output="\uf57F"
      fi
		;;

		7[6-9]|8[0-9]|9[0-9]|100)
      if [ $charging ]; then
        output="\uf584"
      else
        output="\uf578"
      fi
		;;
	esac

echo -e "%{+u}$output $battery%%{-u}"
}

battery
