#!/usr/bin/env bash


battery () {
	battery="$(</sys/class/power_supply/BAT0/capacity)"
	charging="$(</sys/class/power_supply/BAT0/status)"
  output=""

	case "$battery" in
		[0-9]|10)
      #output="\uf582"
      output="\uf244"
		;;

		1[0-9]|2[0-5])
      #output="\uf57A"
      output="\uf243"
		;;

		2[6-9]|3[0-9]|4[0-9]|50)
      #output="\uf57D"
      output="\uf242"
		;;

		5[1-9]|6[0-9]|7[0-5])
      #output="\uf57F"
      output="\uf241"
		;;

		7[6-9]|8[0-9]|9[0-9]|100)
      #output="\uf578"
      output="\uf240"
		;;
	esac

  if [ "$charging" == "Charging" ]; then
    #charging="\u26a1"
    charging="\uf0e7"
  else
    charging=""
  fi

  echo -e "%{+u}$output $battery% $charging%{-u}"
}

battery
