#!/usr/bin/env bash

getMonitorPosition () {
  echo $(xrandr --listactivemonitors | grep -oP "\+[0-9]+(?=.*$1)"| tr -d '[:space:]')
}

launchBar () {
  /usr/local/sbin/admiral -c ~/git/dotfiles/admiral/admiral.toml | lemonbar -u 4 -p -B "#cc000000" -F "#ffeeeeee" -U "$WALLPAPER_MAIN_COLOR" -f "DroidSansMono Nerd Font:size=11" -f "Fira Mono for Powerline:size=11" -f "Font Awesome 5 Free:style=Regular:size=5" -f "siji" -g 1920x25$1 | sh &
}

pkill admiral &>/dev/null
pkill lemonbar &>/dev/null

#/usr/local/sbin/admiral -c ~/gitdotfiles/admiral/admiral.toml | lemonbar -u 2 -p -B "#FF353945" -F "#eeeeee" -f "Fira Code:size=7" -o -1 -f "Font Awesome 5 Free:size=8" -f "siji" -f "Symbola-7" -g 1920x18+0+0 | sh

export output="eDP-1"
notebookPos=$(getMonitorPosition $output)
#/usr/local/sbin/admiral -c ~/git/dotfiles/admiral/admiral.toml | lemonbar -u 3 -p -B "#cc000000" -F "#ffeeeeee" -U "$WALLPAPER_MAIN_COLOR" -f "DroidSansMono Nerd Font" -f "Fira Mono for Powerline:size=11" -f "Font Awesome 5 Free:style=Regular:size=5" -f "siji" -g 1920x25$notebookPos | sh &
launchBar $notebookPos

output="HDMI-1"
hdmiPos=$(getMonitorPosition $output)
echo $hdmiPos
echo $notebookPos

if [ "$hdmiPos" != "" ] && [ "$hdmiPos" != "$notebookPos" ]; then
  launchBar $hdmiPos
fi

