#!/usr/bin/env bash

lauchedBarPositions=()

getMonitorPosition () {
  echo $(xrandr --listactivemonitors | grep -oP "\+[0-9]+(?=.*$1)"| tr -d '[:space:]')
}

getMonitorSize () {
  echo $(xrandr --listactivemonitors | awk -v output=$1 '$2 ~ output { print $3 }' | grep -oP "[0-9]{4}" | head -n1)
}

launchBar () {
  outputPos=$(getMonitorPosition $output)
  outputSize=$(getMonitorSize $output)

  if [[ ! " ${lauchedBarPositions[@]}" =~ "$outputPos" ]]; then
    echo lauchingBar $output ${outputSize}x22${outputPos}
    lauchedBarPositions+=("$outputPos")
    /usr/local/sbin/admiral -c ~/git/dotfiles/admiral/admiral.toml | lemonbar -b -u 2 -p -B "#00000000" -F "#ffeeeeee" \
      -U "${WALLPAPER_MAIN_COLOR:=#ffeeeeee}" \
      -f "Droid Sans Mono for Powerline:style=Regular:size=10" -f "Font Awesome 5 Brands Regular:size=10" -f "Font Awesome 5 Free Solid:size=10" \
      -g ${outputSize}x22${outputPos} | sh &
  else
    echo Ignoring $output
  fi
}

pkill admiral &>/dev/null
pkill lemonbar &>/dev/null

export output="eDP-1"
launchBar

export output="HDMI-1"
launchBar

export output="DP-2"
launchBar

echo Bars lauched