#!/bin/bash

network=$(iwgetid -r)

if [[ $network == "" ]]; then
    exit 0
else
    #signal=$(nmcli dev wifi | grep $network)
    signal=$(cat /proc/net/wireless | awk 'NR==3' | awk '{ print $3 }' | tr -d '.')
fi

echo -n "%{+u}"
echo -n -e "\ue619"
echo -n " $((signal * 100 / 70))%"
echo -n "%{-u}"
