# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# This is where you put your own keybinds. Be Mindful to check as well ~/.config/hypr/configs/Keybinds.conf to avoid conflict
# if you think I should replace the Pre-defined Keybinds in ~/.config/hypr/configs/Keybinds.conf , submit an issue or let me know in DC and present me a valid reason as to why, such as conflicting with global shortcuts, etc etc

# See https://wiki.hyprland.org/Configuring/Keywords/ for more settings and variables
# See also Laptops.conf for laptops keybinds 

$mainMod = SUPER
$files = thunar
$term = kitty
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$ags = /usr/local/bin/ags

# rofi App launcher
# #bindr = $mainMod, $mainMod_L, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window # Super Key to Launch rofi menu
bind = $mainMod, D, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window

bind = $mainMod, A, exec, $term -T gemini-cli gemini-cli chat --model gemini-2.0-flash

##
## AGS
##
## ags overview
#bind = $mainMod, A, exec, pkill rofi || true && $ags -t 'overview'

## Restart AGS
#bind = $mainMod SHIFT, Z, exec, $ags -q && $ags

# Launch terminal
bind = $mainMod, Return, exec, $term  

# Next Calendar Events
bind = $mainMod, O, exec, $ags -t calendar-events

# GitHub PRs
bind = $mainMod, G, exec, xdg-open https://github.com/pulls/review-requested

# Launch file manager
bind = $mainMod, T, exec, $files 

# calculator (qalculate)
bind = $mainMod ALT, C, exec, $UserScripts/RofiCalc.sh 

## pyprland
bind = $mainMod SHIFT, Return, exec, pypr toggle term # Dropdown terminal
bind = $mainMod, Z, exec, pypr zoom # Toggle Zoom

## User Added Keybinds
bind = $mainMod SHIFT, O, exec, $UserScripts/ZshChangeTheme.sh # Change oh-my-zsh theme
# bindn = ALT_L, SHIFT_L, exec, $scriptsDir/SwitchKeyboardLayout.sh # Changing the keyboard layout

bind = $mainMod, j, workspace, m+1
bind = $mainMod, k, workspace, m-1

# For passthrough keyboard into a VM
# bind = $mainMod ALT, P, submap, passthru
#submap = passthru
# to unbind
#bind = $mainMod ALT, P, submap, reset
#submap = reset

bind = $mainMod, Space, cyclenext
bind = $mainMod SHIFT, Space, togglefloating
unbind = $mainMod SHIFT, F
bind = $mainMod SHIFT, F, fullscreen,1

# Group
# bind = $mainMod ALT, right, changegroupactive, f
bind = $mainMod ALT, left, changegroupactive, b
bind = $mainMod ALT, G, togglegroup

# Notebook lid handle
bindl=,switch:on:Lid Switch,exec, sleep 1 && hyprctl dispatch dpms off
bindl=,switch:off:Lid Switch,exec, sleep 1 && hyprctl dispatch dpms on


# Mute Mic
# bind = $mainMod,m, exec, ~/git/dotfiles/bin/mute-default-mic
bindl = $mainMod, m, exec, $scriptsDir/Volume.sh --toggle-mic && $UserScripts/MSTeamsMuteToggle.sh

# Screenshot
bind = $mainMod, P, exec, grim -g "$(slurp)" - | wl-copy && notify-send "Screenshot clipboard"
bind = $mainMod SHIFT, P, exec, grim -g "$(slurp)" - | swappy -f -

#
# Groups
#
$manage_groups=Groups
bind=$mainMod SHIFT,G,submap,$manage_groups

submap=$manage_groups

bind=,l,movewindoworgroup,r
bind=,h,movewindoworgroup,l
bind=,j,movewindoworgroup,d
bind=,k,movewindoworgroup,u

bind = , catchall, submap, reset

submap=reset

#
# Move Workspace
#
$move_workspaces=Move Workspace to (n: eDP-1; h:Left l:Right)
bind=$mainMod SHIFT,m,submap,$move_workspaces

submap=$move_workspaces

bind=,n,movecurrentworkspacetomonitor,eDP-1
bind=,h,movecurrentworkspacetomonitor,l
bind=,l,movecurrentworkspacetomonitor,r

bind = , catchall, submap, reset

submap=reset

