# Group
# bind = $mainMod ALT, right, changegroupactive, f
bind = $mainMod ALT, left, changegroupactive, b
bind = $mainMod ALT, G, togglegroup

# Notebook lid handle
bindl=,switch:on:Lid Switch,exec, sleep 1 && hyprctl dispatch dpms off
bindl=,switch:off:Lid Switch,exec, sleep 1 && hyprctl dispatch dpms on


# Mute Mic
# bind = $mainMod,m, exec, ~/git/dotfiles/bin/mute-default-mic
bindl = $mainMod, m, exec, $scriptsDir/Volume.sh --toggle-mic && $UserScripts/MeetingsAppMuteToggle.sh

bindl = $mainMod ALT, k, exec, /usr/bin/keepassxc

bind = $mainMod, j, workspace, m+1
bind = $mainMod, k, workspace, m-1

unbind = $mainMod, B
bindl = $mainMod, B, workspace, previous


unbind = $mainMod, tab
bindd = $mainMod, tab, Previous Active Workspace, workspace, previous
# bindd = $mainMod SHIFT, tab, previous workspace, workspace, m-1

#
# Groups
#
$manage_groups=Groups
bind=$mainMod SHIFT,G,submap,$manage_groups

submap=$manage_groups

bind=,l,movewindoworgroup,r
bind=,h,movewindoworgroup,l
bind=,j,movewindoworgroup,d
bind=,k,movewindoworgroup,u

bind = , catchall, submap, reset

submap=reset

#
# Move Workspace
#
$move_workspaces=Move Workspace to (n: eDP-1; h:Left l:Right)
bind=$mainMod SHIFT,m,submap,$move_workspaces

submap=$move_workspaces

bind=,n,movecurrentworkspacetomonitor,eDP-1
bind=,h,movecurrentworkspacetomonitor,l
bind=,l,movecurrentworkspacetomonitor,r

bind = , catchall, submap, reset

submap=reset

