
input {
  kb_layout = br
  kb_variant = thinkpad
  kb_model =
  kb_options = caps:escape
  kb_rules =
  repeat_rate = 50
  repeat_delay = 300
  
  sensitivity = 0 #mouse sensitivity
  #accel_profile =     # flat or adaptive or blank or EMPTY means libinput’s default mode
  numlock_by_default = true
  left_handed = false
  follow_mouse = 2
  float_switch_override_focus = false
}


device {
    name = keychron-k6 
    kb_layout = us_custom
    kb_options = caps:escape
    kb_model =
    kb_variant = 
}
