#
# MY CUSTOM Rules
#

windowrule = tag +projects, match:class ^(cursor)$

windowrule = tag +meetings, match:title ^(Círculo.*)$
windowrule = tag +meetings, match:title ^(Microsoft Teams.*)$

windowrule = tag +im, match:title ^(Slack)$

windowrule = tag +notes, match:class ^(Logseq)$
windowrule = tag +notes, match:class ^(obsidian)$

windowrule = tag +multimedia, match:title ^(Spotify.*)$

windowrule = tag +browser, match:class ^(firefox_firefox)$

  
# windowrule move to workspace
windowrule = workspace 2, match:tag projects*
windowrule = workspace 3, match:tag browser*
windowrule = workspace 4, match:tag im*
windowrule = workspace 5, match:tag meetings*
windowrule = workspace 6, match:tag notes*
windowrule = workspace 9, match:tag multimedia*


windowrule=maximize on, match:title ^(Círculo.*)$

windowrule=float on,match:class ^(org.keepassxc.KeePassXC)$
windowrule=float on,match:class ^(org.gnome.Calculator)$
windowrulev2=float on,match:class ^(firefox)$,title ^(Library)$
windowrulev2=float on,match:class ^(firefox)$,title ^(.*Sharing Indicator.*)$
windowrulev2=float on,match:title ^(Save File)$
windowrulev2=float on,match:title ^(.* is sharing your screen.)$
windowrulev2=float on,match:title ^(wlay)$
