$background = rgb(140F1C)
$foreground = rgb(F8A6D0)
$color0 = rgb(3F3949)
$color1 = rgb(493B7C)
$color2 = rgb(803A6C)
$color3 = rgb(853A6B)
$color4 = rgb(973A88)
$color5 = rgb(D93A93)
$color6 = rgb(ED1985)
$color7 = rgb(ED77B3)
$color8 = rgb(A6537D)
$color9 = rgb(493B7C)
$color10 = rgb(803A6C)
$color11 = rgb(853A6B)
$color12 = rgb(973A88)
$color13 = rgb(D93A93)
$color14 = rgb(ED1985)
$color15 = rgb(ED77B3)
